default_game_caracteristique:
  game_opened: false
  only_staff: false
  minimum:
    player: 2
    time: 60
    catchtimer: 10
    respawntimer: 5
    flag: 2
    radius: 3
    point: 100
    killpoint: 5
    flagpoint: 1
  maximum:
    player: 1000
    time: 1000
    catchtimer: 1000
    respawntimer: 1000
    flag: 1000
    radius: 1000
    point: 1000
    killpoint: 1000
    flagpoint: 1000
  configurable:
    player: true
    time: true
    catchtimer: true
    respawntimer: true
    flag: true
    radius: true
    point: true
    killpoint: true
    flagpoint: true
