default_game_caracteristique:
  game_opened: false
  only_staff: false
  minimum:
    player: 2
    time: 1
    catchtimer: 10
    catchspeed: 1
    respawntimer: 5
    flag: 2
    radius: 3
    point: 100
    killpoint: 5
    flagpoint: 1
  maximum:
    player: 200
    time: 200
    catchtimer: 200
    catchspeed: 200
    respawntimer: 200
    flag: 300
    radius: 900
    point: 200
    killpoint: 20
    flagpoint: 20
  configurable:
    player: true
    time: true
    catchtimer: true
    catchspeed: true
    respawntimer: true
    flag: true
    radius: true
    point: true
    killpoint: true
    flagpoint: true
