default_game_caracteristique:
  game_opened: false
  only_staff: false
  minimum:
    player: 2
    time: 60
    catchtimer: 10
    catchspeed: 1
    respawntimer: 5
    flag: 2
    radius: 3
    point: 100
    killpoint: 5
    flagpoint: 1
  maximum:
    player: 10
    time: 200
    catchtimer: 20
    catchspeed: 2
    respawntimer: 20
    flag: 3
    radius: 9
    point: 200
    killpoint: 10
    flagpoint: 5
  configurable:
    player: true
    time: true
    catchtimer: false
    catchspeed: true
    respawntimer: true
    flag: true
    radius: true
    point: true
    killpoint: true
    flagpoint: true
